---
## This is play 1
- name: Enable intranet services
  hosts: servera.lab.example.com
  become: "yes"
  tasks:
    - name: latest version of httpd and firewalld installed
      ansible.builtin.yum:
        name:
          - httpd
          - firewalld
        state: present

    - name: test html page is created
      ansible.builtin.copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html
        mode: 0644

    - name: firewalld enabled and running
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits access to httpd service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: "yes"

    - name: httpd enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

## This is play 2
- name: Test intranet web server
  hosts: localhost
  become: "no"
  tasks:
    - name: connect to intranet web server
      ansible.builtin.uri:
        url: http://servera.lab.example.com
        return_content: "yes"
        status_code: 200
