
---
## This is play 1  
- name: Enable intranet services
  hosts: servera.lab.example.com
  become: yes
  tasks:

  # Install apache webserver & enable the service & open firewall ports for the webserver & create a custom index.html file that says "I'm a custom website" in /var/www/html 


  

## This is play 2
- name: Test intranet web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to intranet web server
      uri:
        url: http://servera.lab.example.com
        return_content: yes
        status_code: 200